# Generated by Django 3.2.9 on 2021-12-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_description'),
        ('store', '0005_alter_product_customer'),
    ]

    operations = [
    ]
