# Generated by Django 3.2.9 on 2021-12-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211202_1732'),
        ('store', '0006_merge_20211201_0942'),
    ]

    operations = [
    ]
