# Generated by Django 3.2.9 on 2021-12-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211201_1327'),
        ('store', '0006_merge_20211201_0942'),
    ]

    operations = [
    ]
