# Generated by Django 3.2.9 on 2021-12-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_merge_20211202_1803'),
        ('store', '0007_merge_20211202_1820'),
    ]

    operations = [
    ]
