# Generated by Django 3.2.9 on 2021-12-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211203_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_field',
        ),
    ]
