# Generated by Django 3.2.9 on 2021-12-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_order_placedorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlacedOrder',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_field',
            new_name='order',
        ),
    ]
