# Generated by Django 3.2.9 on 2021-12-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20211203_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
