# Generated by Django 3.2.9 on 2021-12-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20211204_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidOrder', to='store.bid'),
        ),
    ]
